// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: proto/bbmesh.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint32 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bbmesh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bbmesh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_bbmesh_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint32 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bbmesh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bbmesh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_bbmesh_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BBMeshMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*BBMeshMessage_Ping
	//	*BBMeshMessage_Pong
	Content isBBMeshMessage_Content `protobuf_oneof:"content"`
}

func (x *BBMeshMessage) Reset() {
	*x = BBMeshMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bbmesh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BBMeshMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBMeshMessage) ProtoMessage() {}

func (x *BBMeshMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bbmesh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBMeshMessage.ProtoReflect.Descriptor instead.
func (*BBMeshMessage) Descriptor() ([]byte, []int) {
	return file_proto_bbmesh_proto_rawDescGZIP(), []int{2}
}

func (m *BBMeshMessage) GetContent() isBBMeshMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *BBMeshMessage) GetPing() *Ping {
	if x, ok := x.GetContent().(*BBMeshMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *BBMeshMessage) GetPong() *Pong {
	if x, ok := x.GetContent().(*BBMeshMessage_Pong); ok {
		return x.Pong
	}
	return nil
}

type isBBMeshMessage_Content interface {
	isBBMeshMessage_Content()
}

type BBMeshMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type BBMeshMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

func (*BBMeshMessage_Ping) isBBMeshMessage_Content() {}

func (*BBMeshMessage_Pong) isBBMeshMessage_Content() {}

var File_proto_bbmesh_proto protoreflect.FileDescriptor

var file_proto_bbmesh_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x62, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x62, 0x6d, 0x65, 0x73, 0x68, 0x22, 0x24, 0x0a, 0x04,
	0x50, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x24, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x62, 0x0a, 0x0d, 0x42, 0x42, 0x4d, 0x65,
	0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x62, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a,
	0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x62,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e,
	0x67, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x22, 0x5a, 0x20,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x72, 0x54, 0x6f, 0x6d,
	0x6b, 0x69, 0x6e, 0x73, 0x6f, 0x6e, 0x2f, 0x42, 0x42, 0x4d, 0x65, 0x73, 0x68, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bbmesh_proto_rawDescOnce sync.Once
	file_proto_bbmesh_proto_rawDescData = file_proto_bbmesh_proto_rawDesc
)

func file_proto_bbmesh_proto_rawDescGZIP() []byte {
	file_proto_bbmesh_proto_rawDescOnce.Do(func() {
		file_proto_bbmesh_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bbmesh_proto_rawDescData)
	})
	return file_proto_bbmesh_proto_rawDescData
}

var file_proto_bbmesh_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_bbmesh_proto_goTypes = []interface{}{
	(*Ping)(nil),          // 0: bbmesh.Ping
	(*Pong)(nil),          // 1: bbmesh.Pong
	(*BBMeshMessage)(nil), // 2: bbmesh.BBMeshMessage
}
var file_proto_bbmesh_proto_depIdxs = []int32{
	0, // 0: bbmesh.BBMeshMessage.ping:type_name -> bbmesh.Ping
	1, // 1: bbmesh.BBMeshMessage.pong:type_name -> bbmesh.Pong
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_bbmesh_proto_init() }
func file_proto_bbmesh_proto_init() {
	if File_proto_bbmesh_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bbmesh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bbmesh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bbmesh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BBMeshMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_bbmesh_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*BBMeshMessage_Ping)(nil),
		(*BBMeshMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bbmesh_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bbmesh_proto_goTypes,
		DependencyIndexes: file_proto_bbmesh_proto_depIdxs,
		MessageInfos:      file_proto_bbmesh_proto_msgTypes,
	}.Build()
	File_proto_bbmesh_proto = out.File
	file_proto_bbmesh_proto_rawDesc = nil
	file_proto_bbmesh_proto_goTypes = nil
	file_proto_bbmesh_proto_depIdxs = nil
}
